### ISSUE TITLE
Color scheme in the Events page

### ISSUE THREAD

**Issue by thenicekat** [Department-of-Technical-Arts/pearl-website-2023#3]
![image](https://github.com/Department-of-Technical-Arts/pearl-website-2023/assets/28446977/51b234cb-5920-467d-b547-14d43d19e12e)

@manaschubby I think we need a better color scheme

**Comment by thenicekat** [comment]
The background in the passes page can be brought to the events page as well?

**Comment by manaschubby** [comment]
Color scheme from the SU 🫠🫠

**Comment by manaschubby** [comment]
Maybe we can make the filter and sort icon white....
